### PR TITLE
Enable serpent

### PR DESCRIPTION
**Pull request by leonardt**

### CODE REVIEW

**Comment by steveri** [comment]
Yeah, okay, go ahead and leave serpent commented out for now.  We can push to master without the serpent checks, and I will work on fixing serpent some other time...

**Comment by steveri** [comment]
@leonardt FYI I am using this branch to debug the serpent...which I assume was your original intent in creating it...

**Comment by leonardt** [comment]
@steveri yes, that's the exact use of this branch, debug away!

**Comment by leonardt** [comment]
@steveri looks like this is working now, in the spirit of a "review" based process, I can make this merge as an "approving reviewer" if you think it's ready to go?

**Comment by steveri** [comment]
Hey HEY!  Looks like we're finally ready to go on this one.  Note we have passed both SMT and Serpent tests (below).  Who would like to do the honors?

>TEST SUMMARY BEGIN 14:39:56
> Core tests
>   14:48:48 TEST RESULT pointwise PASSED
>   14:49:12 TEST RESULT conv_1_2 PASSED
>   14:49:38 TEST RESULT conv_2_1 PASSED
>   14:50:07 TEST RESULT conv_3_1 PASSED
>   14:53:52 TEST RESULT conv_bw PASSED
> Serpent tests
>   14:54:07 TEST RESULT pointwise PASSED
>   14:54:16 TEST RESULT conv_1_2 PASSED
>   14:54:26 TEST RESULT conv_2_1 PASSED
>   14:54:39 TEST RESULT conv_3_1 PASSED
>   14:56:29 TEST RESULT conv_bw PASSED

**Comment by leonardt** [comment]
Great work Steve!

**Pull request merged**
