### PR TITLE
Move travis stuff into a shell script

### PR DESCRIPTION
**Pull request by jameshegarty**
Please verify that all tests are still being run correctly in Travis.

### CODE REVIEW

**Comment by cdonovick** [comment]
I would prefer to see install dependencies split into a separate script from install. 
Also instead of pulling all the git repos I think we should make them submodules.

**Comment by cdonovick** [comment]
For the uninitiated https://git-scm.com/docs/git-submodule

**Comment by leonardt** [comment]
@cdonovick We discussed submodules at an earlier point, there were a couple tradeoffs but James and I are still open to using them. We can open a separate issue (and eventual PR) to discuss, our main worry was that submodules won't necessarily point to the latest master commit. One workaround would be instituting a policy that any merges into master of a submodule would require a submodule bump in the CGRAFlow repo (we would need to enforce this policy). Otherwise, submodules could advance their master branches and break the flow without knowing.

However I think we can keep this pull request focused on the install script and do the submodule discussion/changes independently.

WRT the install dependencies, is that covered by what I mention in https://github.com/StanfordAHA/CGRAFlow/issues/20?

**Comment by cdonovick** [comment]
Good point regarding submodules I have forgotten about the whole pointing to a specific commit thing.  

https://github.com/StanfordAHA/CGRAFlow/issues/20 is precisely what I had in mind

**Pull request merged**
