### PR TITLE
Automatic branch testing

### PR DESCRIPTION
**Pull request by cdonovick**
Automatic branch testing

Usage:
```
./brancher.sh <SUBPROJECT_1> <BRANCH_1> <SUBPROJECT_2> <BRANCH_2> ...
```
Creates a branch on CGRAflow which checkouts `SUBPROJECT_1 BRANCH_1 ...` instead of checking out master

```
 ./cleanup.sh <SUBPROJECT_1> <BRANCH_1> <SUBPROJECT_2> <BRANCH_2> ...
```
Deletes the branch created by `brancher.sh`

Example:
```
./brancher.sh halide test coreir intergration
#makes a branch named halide_test_coreir_integration which pulls from 
#halide:test and coreir:integration
#pushes the branch to github

./cleanup.sh halide test coreir intergration
#deletes halide_test_coreir_integration both locally and from remote
```

While I did my best to do error checking in these scripts I make no promises that incorrect usage will not cause incorrect behavior.

### CODE REVIEW

**Comment by jameshegarty** [comment]
Ok with me. But I would recommend putting these scripts in a 'scripts/' directory of 'misc/' directory instead of root.

**Comment by steveri** [comment]
Very nice!  

I agree with James, however, they should probably be in a subdirectory, in order to keep top level clean...I like "scripts/" better than "misc/" (sometimes I use "bin/" or "utils/")

**Comment by cdonovick** [comment]
I moved the scripts to `./scripts/` as requested

**Comment by cdonovick** [comment]
I am going to go ahead and merge.

**Pull request merged**
